!
hostname SW-CORE
!
no ip domain-lookup
!
vlan 10
 name MANAGEMENT
!
vlan 20
 name USERS
!
vlan 30
 name DEVELOPMENT
!
vlan 40
 name SERVERS
!
vlan 50
 name DMZ
!
vlan 99
 name NATIVE
!
interface GigabitEthernet0/1
 description TRUNK-TO-PALO-ALTO
 switchport mode trunk
 switchport trunk native vlan 99
 switchport trunk allowed vlan 10,20,30,40,50,99
!
interface GigabitEthernet0/2
 description TRUNK-TO-SW-ACCESS-01
 switchport mode trunk
 switchport trunk native vlan 99
 switchport trunk allowed vlan 10,20,30,40,50,99
!
interface GigabitEthernet0/3
 description TRUNK-TO-SW-ACCESS-02
 switchport mode trunk
 switchport trunk native vlan 99
 switchport trunk allowed vlan 10,20,30,40,50,99
!
interface Vlan10
 description Management
 ip address 192.168.10.2 255.255.255.0
 no shutdown
!
ip default-gateway 192.168.10.1
!
end